/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LobbyLobbyIdRouteImport } from './routes/lobby.$lobbyId'
import { Route as SessionGameIdLobbyIdRouteImport } from './routes/session.$gameId.$lobbyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyLobbyIdRoute = LobbyLobbyIdRouteImport.update({
  id: '/lobby/$lobbyId',
  path: '/lobby/$lobbyId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionGameIdLobbyIdRoute = SessionGameIdLobbyIdRouteImport.update({
  id: '/session/$gameId/$lobbyId',
  path: '/session/$gameId/$lobbyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lobby/$lobbyId': typeof LobbyLobbyIdRoute
  '/session/$gameId/$lobbyId': typeof SessionGameIdLobbyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lobby/$lobbyId': typeof LobbyLobbyIdRoute
  '/session/$gameId/$lobbyId': typeof SessionGameIdLobbyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/lobby/$lobbyId': typeof LobbyLobbyIdRoute
  '/session/$gameId/$lobbyId': typeof SessionGameIdLobbyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/lobby/$lobbyId' | '/session/$gameId/$lobbyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/lobby/$lobbyId' | '/session/$gameId/$lobbyId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/lobby/$lobbyId'
    | '/session/$gameId/$lobbyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LobbyLobbyIdRoute: typeof LobbyLobbyIdRoute
  SessionGameIdLobbyIdRoute: typeof SessionGameIdLobbyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$lobbyId': {
      id: '/lobby/$lobbyId'
      path: '/lobby/$lobbyId'
      fullPath: '/lobby/$lobbyId'
      preLoaderRoute: typeof LobbyLobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$gameId/$lobbyId': {
      id: '/session/$gameId/$lobbyId'
      path: '/session/$gameId/$lobbyId'
      fullPath: '/session/$gameId/$lobbyId'
      preLoaderRoute: typeof SessionGameIdLobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LobbyLobbyIdRoute: LobbyLobbyIdRoute,
  SessionGameIdLobbyIdRoute: SessionGameIdLobbyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
